# -*- coding: utf-8 -*-
"""Score.ipynb

Automatically generated by Colab.

Merged from score.py and score (1).py
"""

score_str = input().split()
scores_int = []
total_score = 0
count_failing = 0

for s in score_str:
    s_int = int(s)
    scores_int.append(s_int)
    total_score += s_int
    if s_int < 60:
        count_failing += 1

print("不及格人數:", count_failing)

if len(scores_int) > 0:
    average_score = total_score / len(scores_int)
    print("平均分數:", average_score)
    
    max_score = max(scores_int)
    min_score = min(scores_int)
    print("最高分:", max_score, "最低分:", min_score)
else:
    print("沒有分數輸入，無法計算平均。")
