# -*- coding: utf-8 -*-
"""Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eWVSZglgPtdbeNkn5DF7j8Rke2zSTS_g
"""

Score = input().split()
countF = 0
for i in Score:
    if int(i) < 60:
        countF += 1
print("不及格人数：", countF)