# -*- coding: utf-8 -*-
"""score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ywCzxHUGJKi8BniyGmeCTF4zGCaIBr3C
"""



score_str = input().split()
scores_int = []
total_score = 0
count_failing = 0

for s in score_str:
    s_int = int(s)
    scores_int.append(s_int)
    total_score += s_int
    if s_int < 60:
        count_failing += 1

print("不及格人數:", count_failing)

if len(scores_int) > 0:
    average_score = total_score / len(scores_int)
    print("平均分數:", average_score)
else:
    print("沒有分數輸入，無法計算平均。")



